FROM node:22-alpine AS builder

WORKDIR /src/apps/restaurant-services-catalog

COPY apps/restaurant-services-catalog/package*.json ./
RUN npm ci

COPY apps/restaurant-services-catalog ./
RUN npm run build

FROM nginx:1.27-alpine

COPY infra/docker/nginx-catalog.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /src/apps/restaurant-services-catalog/dist /usr/share/nginx/html

EXPOSE 80
